name: build test

on: [push]

jobs:
  linux-native-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev default-jdk
    - name: build
      run: ./gradlew installMinigiacLinux64Executable

  linux-native-cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev cmake
    - name: build
      run: mkdir cbuild && cd cbuild && cmake .. && make

  linux-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install git default-jdk
    - name: build
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        ./gradlew installEmsdk
        cd emsdk
        ln -s . emsdk-portable
        mkdir emscripten
        cd emscripten
        ln -s ../upstream/emscripten latest
        cd ../..
        ./gradlew activateEmsdk createGiacWasmJs

  linux-nodejs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev npm nodejs
    - name: build
      run: npm install

  mac-native-cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: brew install gmp mpfr readline coreutils cmake
    - name: build
      run: mkdir cbuild && cd cbuild && cmake .. && make

  mac-nodejs:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: brew install gmp mpfr readline coreutils node
    - name: build
      run: npm install

