name: build test

on: [push]

# Lots of jobs are defined below. Their format is:
#
# OS-VARIANT-TOOL
#
# where
#
# OS can be:
#
# * linux or
# * mac or
# * windows_msys2_clang64 or windows_msys2_clang32, or
# * windows64_linux or windows32_linux (when cross-platform build is done for Windows, under Linux),
#
# VARIANT can be:
#
# * native (to obtain a command line application) or
# * wasm (to get a WebAssembly version, to be embedded in a webpage) or
# * jnidll (to get a .DLL file that can be integrated in a Java application as a Java Native Interface),
#
# TOOL can be:
#
# * gradle (the build process is conducted by Gradle) or
# * cmake (the build process is run via CMake) or
# * npm (the build is performed via NPM).

jobs:
  linux-native-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev default-jdk
    - name: build
      run: ./gradlew installMinigiacLinux64Executable

  linux-native-cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential cmake
      # run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev cmake
    - name: build
      run: mkdir cbuild && cd cbuild && cmake .. && make

  linux-wasm-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install git default-jdk
    - name: build
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        ./gradlew installEmsdk
        cd emsdk
        ln -s . emsdk-portable
        mkdir emscripten
        cd emscripten
        ln -s ../upstream/emscripten latest
        cd ../..
        ./gradlew activateEmsdk createGiacWasmJs

  linux-jnidll-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential default-jdk
      # run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev default-jdk
    - name: build
      run: ./gradlew javagiacLinux64SharedLibrary

  windows32_linux-jnidll-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential binutils-mingw-w64-i686 g++-mingw-w64-i686 gcc-mingw-w64-i686 mingw-w64-i686-dev default-jdk
    - name: build
      run: ./gradlew javagiacWin32SharedLibrary

  windows64_linux-jnidll-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential binutils-mingw-w64-x86-64 g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 mingw-w64-x86-64-dev default-jdk
    - name: build
      run: ./gradlew javagiacWin64SharedLibrary

  linux-nodejs-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev npm nodejs
    - name: build
      run: npm install

  mac-native-cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: brew install coreutils cmake
      # run: brew install gmp mpfr readline coreutils cmake
    - name: build
      run: mkdir cbuild && cd cbuild && cmake .. && make

  mac-jnidll-gradle:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: brew install coreutils java11
      # run: brew install gmp mpfr coreutils java11
    - name: build
      run: ./gradlew javagiacOsx_am64SharedLibrary

  windows_msys2_clang64-native-cmake:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        update: true
        install: >-
          base-devel
          mingw-w64-clang-x86_64-cc
          mingw-w64-clang-x86_64-cmake
          mingw-w64-clang-x86_64-make
    - name: build
      run: mkdir cbuild && cd cbuild && CC=clang CXX=clang++ cmake -G "MinGW Makefiles" .. && mingw32-make

  windows_msys2_clang32-native-cmake:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG32
        update: true
        install: >-
          base-devel
    - name: prerequisites2
      run: |
          C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'echo' '[clang32]' >> '/etc/pacman.conf'"
          C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'echo' 'Include = /etc/pacman.d/mirrorlist.mingw' >> '/etc/pacman.conf'"
          C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'pacman' '--noconfirm' '-Syuu' '--overwrite' '*'"
          rem C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'pacman' '--noconfirm' '-S' '--needed' '--overwrite' '*' 'mingw-w64-clang-i686-cc' 'mingw-w64-clang-i686-cmake' 'mingw-w64-clang-i686-make' 'mingw-w64-clang-i686-gmp' 'mingw-w64-clang-i686-mpfr'"
          C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'pacman' '--noconfirm' '-S' '--needed' '--overwrite' '*' 'mingw-w64-clang-i686-cc' 'mingw-w64-clang-i686-cmake' 'mingw-w64-clang-i686-make'"
      shell: cmd
    - name: build
      run: mkdir cbuild && cd cbuild && CC=clang CXX=clang++ cmake -G "MinGW Makefiles" .. && mingw32-make

# Currently broken:
#  mac-nodejs-npm:
#    runs-on: macos-11
#    steps:
#    - uses: actions/checkout@v1
#    - name: prerequisites
#      run: brew install gmp mpfr readline coreutils node
#    - name: build
#      run: npm install

