name: build test

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libgmp-dev libmpfr-dev default-jdk
    - name: build
      run: ./gradlew installMinigiacLinux64Executable
