name: publish

on:
  push:
    tags:
      - '*'

jobs:
  linux-jnidll-gradle:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@v3
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential default-jdk
    - name: build
      run: ./gradlew javagiacLinux64Jar
    - name: publish
      run: |
        mvn --batch-mode deploy:deploy-file -Durl=https://maven.pkg.github.com/kovzol/giac-1 \
          -DrepositoryId=github -Dfile=build/distributions/javagiac/javagiac-linux64-natives-linux-amd64.jar \
          -Dclassifier=natives-linux-amd64 -DgroupId=com.github -DartifactId=javagiac -Dversion=$CI_REF_NAME_SLUG
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  mac-jnidll-gradle:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@v3
    - name: prerequisites
      run: brew install coreutils java11
    - name: build
      run: ./gradlew javagiacMacJarLocal
    - name: publish
      run: |
        mvn --batch-mode deploy:deploy-file -Durl=https://maven.pkg.github.com/kovzol/giac-1 \
          -DrepositoryId=github -Dfile=build/distributions/javagiac/javagiac-mac-natives-macosx-universal.jar \
          -Dclassifier=natives-macosx-universal -DgroupId=com.github -DartifactId=javagiac -Dversion=$CI_REF_NAME_SLUG
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
